### ISSUE TITLE
MW inflected form link 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-homepage#11]
Usha suggests that we add a link to the 'MW inflected forms' at the Monier-Williams dictionary line on the homepage
![image](https://user-images.githubusercontent.com/6393033/200094552-51f7ca00-29ab-4c79-b0df-9caccd86feff.png)

The MW inflected form  link at the bottom (Miscellany) can remain as is.

This will make the inflected form display more visible to users.

**Comment by gasyoun** [comment]
> This will make the inflected form display more visible to users.

She might be right. But it sure should be short, otherwise too much data in a row.

**Comment by funderburkjim** [comment]
Inflected forms link added to MW line in homepage.
![image](https://user-images.githubusercontent.com/6393033/202000597-306dcdff-8d7d-4247-abf6-e0a1f9015481.png)
