### ISSUE TITLE
Link to DSAL Pali-English dictionary

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-homepage#14]
@maltenth requests that a link to the Pali-English dictionary at DSAL be added in the homepage display after Tamil Lexicon.

**Comment by funderburkjim** [comment]
This link added.

**Comment by gasyoun** [comment]
> Pali-English dictionary at DSAL be added in the homepage display after Tamil Lexicon.

Why only this and not the others at DSAL?

**Comment by funderburkjim** [comment]
This added as a favor to Thomas.

We might consider a section on the homepage for links to non-Cologne resources.
