### ISSUE TITLE
Time to update the homepage

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-homepage#15]
Dear Jim,
Kindly update the homepage. I am particularly interested in the version and citation part.
```
Cologne Digital Sanskrit Dictionaries, version 2.4.79,
Cologne University, accessed on April 13, 2023,
https://www.sanskrit-lexicon.uni-koeln.de
```

I want it to read somewhere in September 2023 rather than current April 2023.

**Comment by gasyoun** [comment]
> update the homepage

Good that only this part is of interest to you ))
