### ISSUE TITLE
Link to Scanned Edition of PGN

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-homepage#3]
An attempt is being made to deal with old or non-functional links from the home page at Cologne.

This note declares the change of link for the Scanned edition of PGN (Gupta Inscriptions)  on the Cologne Home page.

See the [commit](https://github.com/sanskrit-lexicon/csl-homepage/commit/00a3a16c357ec2aa66fa67eef97f225e7ba70f47).

Also see the readme.txt file in the referenced webscan directory  (Only available on Cologne server. Not in a
repository).

**Comment by gasyoun** [comment]
> change of link for the Scanned edition of PGN (Gupta Inscriptions)

Tried it a few times, but of no use in my work. Good to have it for collection.
