### ISSUE TITLE
Lanman added to homepage

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-homepage#4]
The Lanman dictionary displays added to sanskrit-lexicon homepage.

![image](https://user-images.githubusercontent.com/6393033/99920300-947e2400-2cf0-11eb-8a31-867e47db432d.png)

Hope others will check it out.

A useful feature is that there are links in many Vocabulary entries to
* Whitney Sanskrit Grammar
* Lanman's reader  (text instances of vocabulary)

**Comment by gasyoun** [comment]
> Hope others will check it out.

You bet! I'm a big fan of Lanman. Typographically it is above all other books, the more the ones printed nowadays. And although that is one of the glossary kind of, it is of greatest interest to the student of Sanskrit. It is not used widely any longer in education in US, the worse for education. Congratulations, Jim, you've been preparing it for long time, as I can see.

> Whitney Sanskrit Grammar

The interlinking - is a must in HTML and is sooo quick, it's easy, yet sooo effective.

> <title>LAN List</title>
><span id="title">Lanman Sanskrit Reader Dictionary</span>

Let's make the `title` not only good and short for a tab, but one that can be actually googled. `LAN List` is too esoteric. `Lanman Sanskrit Reader Dictionary + year` would make more sense.

![18s](https://user-images.githubusercontent.com/80761/100006710-f9fb0f00-2ddb-11eb-8dc3-98258fbe5f26.JPG)

Let's decrease font size for the superscript letters as per book. Now way too big.

> √pad: cf. (greek)

We want to ask to help us with the Greek, do not we?

**Comment by funderburkjim** [comment]
@gasyoun Need you to provide Worldcat reference and Bibliographic entry for LAN:
![image](https://user-images.githubusercontent.com/6393033/100030756-40437480-2dc2-11eb-86c8-eb0bbe814baa.png)

like you did for other dictionaries (e.g. [Benfey](http://localhost/cologne/ben/web/).

**Comment by gasyoun** [comment]
>Worldcat reference

https://www.worldcat.org/title/sanskrit-reader-with-vocabulary-and-notes/oclc/1120214238

LANMAN, C. R. (1888). A Sanskrit Reader: with vocabulary and notes. Ginn and Co, Boston, U.S.A.

**Comment by funderburkjim** [comment]
Thanks!  Now installed.

**Comment by funderburkjim** [comment]
> decrease font size for the superscript letters as per book.

Changed css font-size for 'sup' to 'x-small', for Lanman.
![image](https://user-images.githubusercontent.com/6393033/100487239-9d4a6d80-30d5-11eb-8842-8ac47988f3a3.png)

Result is that superscript is now about 10px,  versus prior 13px.

OK?

**Comment by gasyoun** [comment]
> OK?

Perfect.

**Comment by funderburkjim** [comment]
I think all issues mentioned here are now resolved.
