### ISSUE TITLE
Simplify  link to simple-search

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-homepage#5]
This pertains to the simple-search link on homepage:

![image](https://user-images.githubusercontent.com/6393033/101552400-ce9e2580-3980-11eb-95fb-7db967371aae.png)

Before the change, clicking brought up this page:

![image](https://user-images.githubusercontent.com/6393033/101552575-115ffd80-3981-11eb-980b-2f4f639d9a20.png)

After the change, it simplifies the address and title of the page:

![image](https://user-images.githubusercontent.com/6393033/101552677-41a79c00-3981-11eb-83b8-ae749d1079cd.png)

**Comment by funderburkjim** [comment]
The change makes use of the .htaccess rewrite rule for simple search.

A similar change is made for the homepage of local installations.

**Comment by gasyoun** [comment]
>The change makes use of the .htaccess rewrite rule for simple search.

Hurray!

Let us do the last step. Cut off WWW. No need of it, economy of 3 letters and a dot. `sanskrit-lexicon` is a subdomain already. No need to have a subdomain of a subdomain, really, really.

> https://www.sanskrit-lexicon.uni-koeln.de/simple/

to

> https://sanskrit-lexicon.uni-koeln.de/simple/

**Comment by funderburkjim** [comment]
If you look at the source for home page, you'll see
`<a href="/simple/"><b>Simple-Search</b></a>`.

The rewrite rule inserts the www.  

If we change the home page link to 
`<a href="//sanskrit-lexicon.uni-koeln.de/simple/"><b>Simple-Search</b></a>`
then the www goes away.

Do you confirm?

**Comment by gasyoun** [comment]
> Do you confirm?

I do confirm. For us it's of no value at all.

**Comment by gasyoun** [comment]
`https://www.sanskrit-lexicon.uni-koeln.de/simple`

does not work

`https://www.sanskrit-lexicon.uni-koeln.de/simple/`

only `simple/` does with `/` at end of URLs.

**Comment by funderburkjim** [comment]
https://sanskrit-lexicon.uni-koeln.de/simple  now works.

Glad you are finding these edge cases.

**Comment by gasyoun** [comment]
> Glad you are finding these edge cases.

20 years doing it.

![simple](https://user-images.githubusercontent.com/80761/101693736-173e0780-3a83-11eb-800d-48a42064e8b3.JPG)

This is what I get from the URL above.

**Comment by funderburkjim** [comment]
Bug now fixed.

![image](https://user-images.githubusercontent.com/6393033/101699941-2d7ba180-3a4a-11eb-9f29-e2d175c1aef8.png)

**Comment by gasyoun** [comment]
> Bug now fixed.

Thanks.
