### ISSUE TITLE
AP90 publication date to 1920

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-homepage#6]
Changed publication date for AP90 from 1890 to 1920, since the Cologne digitization is based on 3rd edition of 1920.

**Comment by drdhaval2785** [comment]
Does it mean that we have to change the scripts to use ap20 instead of ap90? Or for internal works, ap90 abbreviation is just fine?

**Comment by funderburkjim** [comment]
We can leave it as ap90.  It's just an arbitrary identifier.

**Comment by drdhaval2785** [comment]
Great.

**Comment by gasyoun** [comment]
> ap90. It's just an arbitrary identifier.

Agree.

**Comment by funderburkjim** [comment]
I goofed in the dates for ap90/ae.

Now  ap90 appears with '1890',
and ae appears with '1920'.

See https://github.com/sanskrit-lexicon/COLOGNE/issues/359
